package ru.otus.tables;

import ru.otus.animals.Animal;
import ru.otus.animals.Color;
import ru.otus.database.IDBConnectionManager;
import ru.otus.factory.AnimalFactory;
import ru.otus.factory.AnimalType;
import ru.otus.tables.interfaces.IAnimalTable;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class AnimalTable extends AbsTable implements IAnimalTable {

    private final AnimalFactory factory;

    public AnimalTable(AnimalFactory factory, IDBConnectionManager idbConnectionManager) throws SQLException {
        super("animals", idbConnectionManager);
        this.factory = factory;
        columns.put("id", "bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY");
        columns.put("name", "varchar(128)");
        columns.put("age", "bigint");
        columns.put("weight", "bigint");
        columns.put("color", "varchar(32)");
        columns.put("type","varchar(16)");
        create();
    }

    @Override
    public List<Animal> findAllAnimals() {
        String sqlQuery = "SELECT name, age, weight, color, type FROM " + tableName;

        return getAnimalsByQuery(sqlQuery);
    }

    @Override
    public List<Animal> findAnimalsByType(AnimalType type) {
        String sqlQuery = "SELECT name, age, weight, color, type FROM " + tableName 
                + " WHERE type = '" + type.name() + "'";

        return getAnimalsByQuery(sqlQuery);
    }
    @Override
    public Animal findAnimalByName(String name) {
        String sqlQuery = "SELECT name, age, weight, color, type FROM " + tableName
                + " WHERE name = '" + name + "'";

        ArrayList<Animal> animalsByQuery = getAnimalsByQuery(sqlQuery);
        if(animalsByQuery.isEmpty()){
            return null;
        }
        return animalsByQuery.getFirst();
    }

    private ArrayList<Animal> getAnimalsByQuery(String sqlQuery) {
        ArrayList<Animal> animals = new ArrayList<>();
        try(ResultSet rs = idbConnectionManager.executeQuery(sqlQuery)) {

            while (rs.next()) {
                String name = rs.getString("name");
                int age = rs.getInt("age");
                int weight = rs.getInt("weight");
                String color = rs.getString("color");
                String type = rs.getString("type");
                Animal animal = factory.create(AnimalType.fromString(type));
                animals.add(animal);
                animal.setName(name);
                animal.setAge(age);
                animal.setWeight(weight);
                animal.setColor(Color.fromString(color));
            }
        }catch (SQLException e){
            throw new RuntimeException(e);
        }
        return animals;
    }

    @Override
    public void create(Animal animal) {
        String sqlQuery = "INSERT INTO " + tableName + "(";
        sqlQuery += "name, age, weight, color, type";
        sqlQuery+=") VALUES (";
        sqlQuery += "'" + animal.getName() + "'," + animal.getAge() + "," +
                animal.getWeight() + ",'" + animal.getColor().name() + "','" +
                animal.getType().name()+"'";
        sqlQuery +=")";

        try {
            idbConnectionManager.executeNoResult(sqlQuery);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
    @Override
    public void updateAnimalByName(Animal animal) {
        String sqlQuery = "UPDATE " + tableName + " SET ";
        sqlQuery += "age = "+ animal.getAge() + ", ";
        sqlQuery+= "weight = " + animal.getWeight() + ", ";
        sqlQuery += "color = '" + animal.getColor().name() + "'";

        try {
            idbConnectionManager.executeNoResult(sqlQuery);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
